export default  {
  OPENPOP: 'OPENPOP',
  CLOSEPOP: 'CLOSEPOP',
  INPUTVALUE: 'INPUTVALUE',
  CLICKOK: 'CLICKOK',
  SELECTVALUE: 'SELECTVALUE',
  ADDMONTH: 'ADDMONTH',
  SUBMONTH: 'SUBMONTH',
  ADDYEAR: 'ADDYEAR',
  SUBYEAR: 'SUBYEAR',
}
